global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "WebSocketChat"
#    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["webs1:8443", "webs2:8443"]